yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/users/urls.py
from django.contrib.auth import views as user_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        user_views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        user_views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_change/',
        user_views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        user_views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        user_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        user_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        user_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        user_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/comments_list.html
<div class="media-body small">
  <a href="{% url 'posts:profile' comment.author.username %}">
    {{ comment.author.username }}
  </a>
  {{ comment.text|linebreaks }}
</div>

yatube/templates/includes/footer.html
<p>
  © {{ year }} Copyright <span style="color:red">Ya</span>tube
</p>

yatube/templates/includes/form_comment.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in post.comments.all %}
  {% include 'includes/comments_list.html' %}
{% endfor %}

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_fields.html
{% for field in form %}
  {% load user_filters %}
  <div class="form-group row my-3 p-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help"
             class="form-text text-muted">
      {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top navbar-light"
     style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30"
        class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar-menu"
            aria-controls="navbar-menu"
            aria-expanded="false"
            aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-menu">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% with request.resolver_match.view_name as active %}
          <li class="nav-item">
            <a class="nav-link text-dark
              {% if active  == 'about:author' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{% url 'about:author' %}"
            >
              Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark
              {% if active  == 'about:tech' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{% url 'about:tech' %}"
            >
              Технологии
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-dark
              {% if active  == 'posts:post_create' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white
              {% if active  == 'users:password_change' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{% url 'users:password_change' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white"
               href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark
              {% if active == 'posts:profile' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{% url 'posts:profile' user.username %}"
            >
            Пользователь: <b>{{ user.username }}</b>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-white
              {% if active  == 'users:login' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white
              {% if active  == 'users:signup' %}
                btn btn-primary px-2 me-2 text-white
              {% endif %}"
               href="{%  url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>
<br>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">
        Первая
      </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_elements.html
{% load thumbnail %}
<div class="card shadow">
  <div class="card-header">
    Автор: {{ post.author.get_full_name }}
    {% if author_posts %}
      <a href="{% url 'posts:profile' post.author %}">
        все посты пользователя
      </a>
    {% endif %}
  </div>
  <div class="card-body">
    <h6 class="card-title text-secondary">
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </h6>
    {% thumbnail post.image "960x600" crop="center" upscale=True as im %}
      <img class="card-img top" src="{{ im.url }}" alt="picture 960x339">
    {% endthumbnail %}
    <p class="card-text">
      {{ post.text|linebreaks|truncatewords:50 }}
    </p>
    {% if post.comments.exists %}
      <p>
        <a class="card-text text-secondary small"
           data-bs-toggle="collapse"
           href="#CollapseComments{{ post.id }}"
           aria-expanded="false"
           aria-controls="CollapseComments{{ post.id }}"
        >
          Комментарии: {{ post.comments.count }}
        </a>
      </p>
        <div class="collapse" id="CollapseComments{{ post.id }}">
          {% for comment in post.comments.all %}
            {% include 'includes/comments_list.html' %}
          {% endfor %}
        </div>
    {% endif %}
    <a
      class="btn btn-outline-primary btn-sm"
      href="{% url 'posts:post_detail' post.pk %}"
    >
      подробная информация
    </a>
  </div>
  {% if post.group and not groups %}
    <div class="card-footer bg-transparent">
      Группа
      <a href="{% url 'posts:group_list' post.group.slug %}">
        {{ post.group.title }}
      </a>
    </div>
  {% endif %}
</div>
{% if not forloop.last %}<br>{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}